import { app } from "electron";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { CompanionCapabilities } from "./protocol";

/**
 * Which phones are allowed to drive this machine.
 *
 * Kept in its own file under userData rather than in the settings store, for two
 * reasons: it holds secrets, and it is written from the network thread on every
 * pairing. Mixing it into the settings file would mean a device pairing could race
 * a settings write and lose someone's theme.
 *
 * A token is a random 256-bit value generated by the host. Only its hash is stored,
 * so the file is not worth stealing - the same reason a password file holds hashes.
 * The phone keeps the token; if the file is deleted, every device simply has to
 * pair again.
 */

export interface TrustedDevice {
  deviceId: string;
  name: string;
  platform: string;
  /** SHA-256 of the token handed to the device. The token itself is never stored. */
  tokenHash: string;
  capabilities: CompanionCapabilities;
  /** ISO timestamps. */
  pairedAt: string;
  lastSeenAt: string;
}

/** Per-feature consent, so a paired phone still cannot do everything by default. */
export interface CompanionPermissions {
  mediaControl: boolean;
  xmbNavigation: boolean;
  touchpad: boolean;
  emulatorSecondScreen: boolean;
  toyBox: boolean;
  ghost: boolean;
}

export const DEFAULT_PERMISSIONS: CompanionPermissions = {
  mediaControl: true,
  xmbNavigation: true,
  touchpad: true,
  emulatorSecondScreen: true,
  toyBox: true,
  // Off by default: Ghost can act on the machine, and a phone asking it to is a
  // bigger step than a phone pressing Down.
  ghost: false,
};

interface RegistryFile {
  devices: TrustedDevice[];
  permissions: CompanionPermissions;
  /** Master switch. False means the server never starts. */
  enabled: boolean;
}

function registryPath(): string {
  return path.join(app.getPath("userData"), "companion.json");
}

function hashToken(token: string): string {
  return crypto.createHash("sha256").update(token).digest("hex");
}

export class DeviceRegistry {
  private data: RegistryFile = { devices: [], permissions: { ...DEFAULT_PERMISSIONS }, enabled: true };
  private loaded = false;

  private load(): void {
    if (this.loaded) return;
    try {
      const parsed = JSON.parse(fs.readFileSync(registryPath(), "utf-8")) as Partial<RegistryFile>;
      this.data = {
        devices: Array.isArray(parsed.devices) ? parsed.devices : [],
        permissions: { ...DEFAULT_PERMISSIONS, ...(parsed.permissions ?? {}) },
        enabled: parsed.enabled !== false,
      };
    } catch {
      this.data = { devices: [], permissions: { ...DEFAULT_PERMISSIONS }, enabled: true };
    }
    this.loaded = true;
  }

  /** Temp file then rename, so a crash mid-write cannot leave a truncated registry. */
  private save(): void {
    try {
      const target = registryPath();
      fs.mkdirSync(path.dirname(target), { recursive: true });
      const temp = `${target}.tmp`;
      fs.writeFileSync(temp, JSON.stringify(this.data, null, 2), "utf-8");
      fs.renameSync(temp, target);
    } catch (err) {
      console.error("[A-X-M] could not save the companion device list:", err);
    }
  }

  isEnabled(): boolean {
    this.load();
    return this.data.enabled;
  }

  setEnabled(enabled: boolean): void {
    this.load();
    this.data.enabled = enabled;
    this.save();
  }

  permissions(): CompanionPermissions {
    this.load();
    return this.data.permissions;
  }

  setPermissions(patch: Partial<CompanionPermissions>): CompanionPermissions {
    this.load();
    this.data.permissions = { ...this.data.permissions, ...patch };
    this.save();
    return this.data.permissions;
  }

  list(): TrustedDevice[] {
    this.load();
    return this.data.devices;
  }

  /**
   * Checks a device's token. Compared as fixed-length hex digests with a constant
   * time comparison, so a caller cannot learn a token by timing the failures.
   */
  verify(deviceId: string, token: string): TrustedDevice | null {
    this.load();
    const device = this.data.devices.find((d) => d.deviceId === deviceId);
    if (!device) return null;

    const given = Buffer.from(hashToken(token), "hex");
    const known = Buffer.from(device.tokenHash, "hex");
    if (given.length !== known.length) return null;
    if (!crypto.timingSafeEqual(given, known)) return null;

    device.lastSeenAt = new Date().toISOString();
    this.save();
    return device;
  }

  /** Issues a fresh token, returning it once. Re-pairing replaces the old one. */
  trust(device: { deviceId: string; name: string; platform: string; capabilities: CompanionCapabilities }): string {
    this.load();
    const token = crypto.randomBytes(32).toString("hex");
    const now = new Date().toISOString();
    const existing = this.data.devices.find((d) => d.deviceId === device.deviceId);

    if (existing) {
      existing.name = device.name;
      existing.platform = device.platform;
      existing.capabilities = device.capabilities;
      existing.tokenHash = hashToken(token);
      existing.lastSeenAt = now;
    } else {
      this.data.devices.push({
        deviceId: device.deviceId,
        name: device.name,
        platform: device.platform,
        capabilities: device.capabilities,
        tokenHash: hashToken(token),
        pairedAt: now,
        lastSeenAt: now,
      });
    }
    this.save();
    return token;
  }

  /** Forgets a device. Its token stops working on its next frame, not eventually. */
  revoke(deviceId: string): boolean {
    this.load();
    const before = this.data.devices.length;
    this.data.devices = this.data.devices.filter((d) => d.deviceId !== deviceId);
    if (this.data.devices.length === before) return false;
    this.save();
    return true;
  }
}
