import { contextBridge, ipcRenderer } from "electron";

const api = {
  getSettings: () => ipcRenderer.invoke("axm:getSettings"),
  setSettings: (partial: Record<string, unknown>) => ipcRenderer.invoke("axm:setSettings", partial),
  toggleFullscreen: () => ipcRenderer.invoke("axm:toggleFullscreen"),
  getGames: () => ipcRenderer.invoke("axm:getGames"),
  scanGames: () => ipcRenderer.invoke("axm:scanGames"),
  launchGame: (gameId: string) => ipcRenderer.invoke("axm:launchGame", gameId),
  setLosslessProfile: (gameId: string, profile: 1 | 2 | 3 | null) =>
    ipcRenderer.invoke("axm:setLosslessProfile", gameId, profile),
  losslessScalingStatus: () => ipcRenderer.invoke("axm:losslessScalingStatus"),
  pickGameFolder: () => ipcRenderer.invoke("axm:pickGameFolder"),
  getMedia: (kind: "photo" | "video" | "music") => ipcRenderer.invoke("axm:getMedia", kind),
  browseMusic: (dirPath: string | null) => ipcRenderer.invoke("axm:browseMusic", dirPath),
  pickMusicFolder: () => ipcRenderer.invoke("axm:pickMusicFolder"),
  pickBackgroundImage: () => ipcRenderer.invoke("axm:pickBackgroundImage"),
  openBrowser: (url: string) => ipcRenderer.invoke("axm:openBrowser", url),
  tvStatus: () => ipcRenderer.invoke("axm:tvStatus"),
  tvLogos: () => ipcRenderer.invoke("axm:tvLogos"),
  tvRefreshLogos: () => ipcRenderer.invoke("axm:tvRefreshLogos"),
  tvLogin: (account: unknown) => ipcRenderer.invoke("axm:tvLogin", account),
  tvCategories: (kind: string, adultUnlocked?: boolean) => ipcRenderer.invoke("axm:tvCategories", kind, adultUnlocked),
  tvLanguages: () => ipcRenderer.invoke("axm:tvLanguages"),
  tvItems: (kind: string, categoryId?: string, adultUnlocked?: boolean) => ipcRenderer.invoke("axm:tvItems", kind, categoryId, adultUnlocked),
  tvEpg: (streamId: string) => ipcRenderer.invoke("axm:tvEpg", streamId),
  tvStreamUrl: (item: unknown) => ipcRenderer.invoke("axm:tvStreamUrl", item),
  tvEpisodes: (seriesId: string) => ipcRenderer.invoke("axm:tvEpisodes", seriesId),
  tvEpisodeUrl: (ep: unknown) => ipcRenderer.invoke("axm:tvEpisodeUrl", ep),
  tvRelayUrl: (url: string) => ipcRenderer.invoke("axm:tvRelayUrl", url),
  companionSettings: (items: unknown[]) => ipcRenderer.send("axm:companionSettings", items),
  companionKeyboard: (prompt: { title: string; label: string; value: string; secret: boolean } | null) => ipcRenderer.send("axm:companionKeyboard", prompt),
  memcardOverview: () => ipcRenderer.invoke("axm:memcardOverview"),
  memcardCreate: (kind: string, name: string) => ipcRenderer.invoke("axm:memcardCreate", kind, name),
  memcardRename: (id: string, name: string) => ipcRenderer.invoke("axm:memcardRename", id, name),
  memcardSlot: (id: string, slot: number) => ipcRenderer.invoke("axm:memcardSlot", id, slot),
  memcardDelete: (id: string) => ipcRenderer.invoke("axm:memcardDelete", id),
  memcardSaves: (id: string) => ipcRenderer.invoke("axm:memcardSaves", id),
  memcardPublish: (id: string, emulator: string) => ipcRenderer.invoke("axm:memcardPublish", id, emulator),
  memcardAdopt: (emulator: string, file: string, name: string) => ipcRenderer.invoke("axm:memcardAdopt", emulator, file, name),
  memcardExport: (id: string, save: string | null, folder: string) => ipcRenderer.invoke("axm:memcardExport", id, save, folder),
  memcardInspect: (file: string) => ipcRenderer.invoke("axm:memcardInspect", file),
  memcardScanDrive: (root: string) => ipcRenderer.invoke("axm:memcardScanDrive", root),
  memcardImportPs1: (id: string, source: string, only?: string[]) => ipcRenderer.invoke("axm:memcardImportPs1", id, source, only),
  memcardImportPs2: (id: string, source: string) => ipcRenderer.invoke("axm:memcardImportPs2", id, source),
  textureDb: () => ipcRenderer.invoke("axm:textureDb"),
  texturePacksFor: (gameId: string) => ipcRenderer.invoke("axm:texturePacksFor", gameId),
  textureInstall: (platform: string, serial: string, slug: string) => ipcRenderer.invoke("axm:textureInstall", platform, serial, slug),
  textureEnable: (platform: string, serial: string, slug: string) => ipcRenderer.invoke("axm:textureEnable", platform, serial, slug),
  textureDisable: (platform: string, serial: string, slug: string) => ipcRenderer.invoke("axm:textureDisable", platform, serial, slug),
  textureDelete: (platform: string, serial: string, slug: string) => ipcRenderer.invoke("axm:textureDelete", platform, serial, slug),
  onTextureProgress: (cb: (p: { slug: string; note: string }) => void) => ipcRenderer.on("axm:textureProgress", (_e, p) => cb(p)),
  apolloStatus: () => ipcRenderer.invoke("axm:apolloStatus"),
  apolloUpdatePatches: () => ipcRenderer.invoke("axm:apolloUpdatePatches"),
  apolloUpdateSaves: () => ipcRenderer.invoke("axm:apolloUpdateSaves"),
  apolloClearCache: () => ipcRenderer.invoke("axm:apolloClearCache"),
  apolloSetLocation: (location: string) => ipcRenderer.invoke("axm:apolloSetLocation", location),
  apolloFind: (ref: { cardId: string; save: string }) => ipcRenderer.invoke("axm:apolloFind", ref),
  apolloPreview: (ref: { cardId: string; save: string }, selections: unknown[]) => ipcRenderer.invoke("axm:apolloPreview", ref, selections),
  apolloApply: (ref: { cardId: string; save: string }, selections: unknown[], note?: string) => ipcRenderer.invoke("axm:apolloApply", ref, selections, note),
  apolloBackups: (ref: { cardId: string; save: string }) => ipcRenderer.invoke("axm:apolloBackups", ref),
  apolloRestore: (ref: { cardId: string; save: string }, backupId?: string) => ipcRenderer.invoke("axm:apolloRestore", ref, backupId),
  apolloCommunity: (ref: unknown) => ipcRenderer.invoke("axm:apolloCommunity", ref),
  apolloImportCommunity: (cardId: string, platform: string, titleId: string, zip: string) => ipcRenderer.invoke("axm:apolloImportCommunity", cardId, platform, titleId, zip),
  companionSendSave: (cardId: string, save: string) => ipcRenderer.invoke("axm:companionSendSave", cardId, save),
  memcardsChanged: () => ipcRenderer.send("axm:memcardsChanged"),
  onMemcardsChanged: (cb: (c: { cardId: string; save: string }) => void) => ipcRenderer.on("axm:memcardsChanged", (_e, c) => cb(c)),
  onApolloProgress: (cb: (p: { note: string }) => void) => ipcRenderer.on("axm:apolloProgress", (_e, p) => cb(p)),
  findSubtitles: (q: { title: string; year?: string; kind: "movie" | "tv"; season?: number; episode?: number }) => ipcRenderer.invoke("axm:findSubtitles", q),
  findLyrics: (artist: string, title: string, album: string, duration: number) => ipcRenderer.invoke("axm:findLyrics", artist, title, album, duration),
  tvDownload: (url: string, name: string, target: string, container: string) => ipcRenderer.invoke("axm:tvDownload", url, name, target, container),
  companionStatus: () => ipcRenderer.invoke("axm:companionStatus"),
  companionForget: (deviceId: string) => ipcRenderer.invoke("axm:companionForget", deviceId),
  companionSetEnabled: (enabled: boolean) => ipcRenderer.invoke("axm:companionSetEnabled", enabled),
  companionMedia: (state: unknown) => ipcRenderer.send("axm:companionMedia", state),
  companionPermissions: (patch: Record<string, boolean>) => ipcRenderer.invoke("axm:companionPermissions", patch),
  onCompanionInput: (callback: (input: unknown) => void) => {
    ipcRenderer.on("axm:companionInput", (_e, input) => callback(input));
  },
  onCompanionPairing: (callback: (p: { code: string | null; deviceName: string }) => void) => {
    ipcRenderer.on("axm:companionPairing", (_e, p) => callback(p));
  },
  onCompanionDevices: (callback: (p: unknown) => void) => {
    ipcRenderer.on("axm:companionDevices", (_e, p) => callback(p));
  },
  onCompanionStatus: (callback: (p: { message: string }) => void) => {
    ipcRenderer.on("axm:companionStatus", (_e, p) => callback(p));
  },
  toyboxSummary: () => ipcRenderer.invoke("axm:toyboxSummary"),
  toyboxByPlatform: (platform: string) => ipcRenderer.invoke("axm:toyboxByPlatform", platform),
  toyboxSearch: (query: string) => ipcRenderer.invoke("axm:toyboxSearch", query),
  toyboxShelf: (filter: unknown) => ipcRenderer.invoke("axm:toyboxShelf", filter),
  toyboxKinds: (platform: string) => ipcRenderer.invoke("axm:toyboxKinds", platform),
  retroEmulators: () => ipcRenderer.invoke("axm:retroEmulators"),
  preparePs3: (gameId: string, trim: unknown) => ipcRenderer.invoke("axm:preparePs3", gameId, trim),
  deleteDiscImage: (gameId: string) => ipcRenderer.invoke("axm:deleteDiscImage", gameId),
  installEmulator: (platform: string) => ipcRenderer.invoke("axm:installEmulator", platform),
  desktopShortcut: (platform: string) => ipcRenderer.invoke("axm:desktopShortcut", platform),
  storeCatalogue: () => ipcRenderer.invoke("axm:storeCatalogue"),
  storeInstall: (item: unknown) => ipcRenderer.invoke("axm:storeInstall", item),
  onStoreArt: (callback: (u: unknown) => void) => ipcRenderer.on("axm:storeArt", (_e, u) => callback(u)),
  toyboxSimulate: (figureId: string | null) => ipcRenderer.invoke("axm:toyboxSimulate", figureId),
  toyboxSimulateRemoval: () => ipcRenderer.invoke("axm:toyboxSimulateRemoval"),
  toyboxNfcStatus: () => ipcRenderer.invoke("axm:toyboxNfcStatus"),
  toyboxDumpsDir: () => ipcRenderer.invoke("axm:toyboxDumpsDir"),
  toyboxLastGame: (figureId: string) => ipcRenderer.invoke("axm:toyboxLastGame", figureId),
  toyboxSetLastGame: (figureId: string, gameId: string) => ipcRenderer.invoke("axm:toyboxSetLastGame", figureId, gameId),
  toyboxSaveCustomTag: (uid: string, label: string, figureId?: string) => ipcRenderer.invoke("axm:toyboxSaveCustomTag", uid, label, figureId),
  onToyboxDetected: (callback: (event: unknown) => void) => ipcRenderer.on("axm:toyboxDetected", (_e, event) => callback(event)),
  onToyboxRemoved: (callback: (event: unknown) => void) => ipcRenderer.on("axm:toyboxRemoved", (_e, event) => callback(event)),
  toyboxSetState: (figureId: string, patch: Record<string, unknown>) =>
    ipcRenderer.invoke("axm:toyboxSetState", figureId, patch),
  openMedia: (filePath: string) => ipcRenderer.invoke("axm:openMedia", filePath),
  getSaves: () => ipcRenderer.invoke("axm:getSaves"),
  browseMedia: (kind: "photo" | "video", dirPath: string | null) =>
    ipcRenderer.invoke("axm:browseMedia", kind, dirPath),
  listBundledAvatars: () => ipcRenderer.invoke("axm:listBundledAvatars"),
  listPictures: () => ipcRenderer.invoke("axm:listPictures"),
  fetchGameIcons: () => ipcRenderer.invoke("axm:fetchGameIcons"),
  onGameIcon: (callback: (update: { gameId?: string; name?: string; url?: string; done?: boolean }) => void) => {
    ipcRenderer.on("axm:gameIcon", (_e, update) => callback(update));
  },
  saveProfile: (profile: { name: string; avatarUrl: string }) => ipcRenderer.invoke("axm:saveProfile", profile),
  cacheImage: (url: string, key: string) => ipcRenderer.invoke("axm:cacheImage", url, key),
  listArtChoices: (gameId: string) => ipcRenderer.invoke("axm:listArtChoices", gameId),
  setGameArt: (gameId: string, url: string) => ipcRenderer.invoke("axm:setGameArt", gameId, url),
  jellyfinDiscover: () => ipcRenderer.invoke("axm:jellyfinDiscover"),
  jellyfinLogin: (server: unknown, username: string, password: string) =>
    ipcRenderer.invoke("axm:jellyfinLogin", server, username, password),
  jellyfinForget: (serverUrl: string) => ipcRenderer.invoke("axm:jellyfinForget", serverUrl),
  jellyfinLibraries: (login: unknown) => ipcRenderer.invoke("axm:jellyfinLibraries", login),
  jellyfinItems: (login: unknown, parentId: string) => ipcRenderer.invoke("axm:jellyfinItems", login, parentId),
  getAnkerStatus: () => ipcRenderer.invoke("axm:getAnkerStatus"),
  getWifiStatus: () => ipcRenderer.invoke("axm:getWifiStatus"),
  getBluetoothStatus: () => ipcRenderer.invoke("axm:getBluetoothStatus"),
  getHardwareInfo: () => ipcRenderer.invoke("axm:getHardwareInfo"),
  getMediaDrives: () => ipcRenderer.invoke("axm:getMediaDrives"),
  getVolumes: () => ipcRenderer.invoke("axm:getVolumes"),
  getControllerDevices: () => ipcRenderer.invoke("axm:getControllerDevices"),
  wifiList: () => ipcRenderer.invoke("axm:wifiList"),
  wifiConnect: (ssid: string, password: string | null) => ipcRenderer.invoke("axm:wifiConnect", ssid, password),
  wifiDisconnect: () => ipcRenderer.invoke("axm:wifiDisconnect"),
  wifiForget: (ssid: string) => ipcRenderer.invoke("axm:wifiForget", ssid),
  btList: () => ipcRenderer.invoke("axm:btList"),
  btPair: (id: string) => ipcRenderer.invoke("axm:btPair", id),
  btUnpair: (id: string) => ipcRenderer.invoke("axm:btUnpair", id),
  getPowerSettings: () => ipcRenderer.invoke("axm:getPowerSettings"),
  setPowerPlan: (guid: string) => ipcRenderer.invoke("axm:setPowerPlan", guid),
  setPowerTimeout: (what: string, onBattery: boolean, minutes: number) => ipcRenderer.invoke("axm:setPowerTimeout", what, onBattery, minutes),
  powerAction: (action: string) => ipcRenderer.invoke("axm:powerAction", action),
  getClock: () => ipcRenderer.invoke("axm:getClock"),
  syncClock: () => ipcRenderer.invoke("axm:syncClock"),
  listTimeZones: () => ipcRenderer.invoke("axm:listTimeZones"),
  setTimeZone: (id: string) => ipcRenderer.invoke("axm:setTimeZone", id),
  fileInfo: (filePath: string) => ipcRenderer.invoke("axm:fileInfo", filePath),
  hostName: () => ipcRenderer.invoke("axm:hostName"),
  listDiscs: () => ipcRenderer.invoke("axm:listDiscs"),
  discTools: () => ipcRenderer.invoke("axm:discTools"),
  importAudioCd: (disc: unknown, target: string, format: string) => ipcRenderer.invoke("axm:importAudioCd", disc, target, format),
  backupDisc: (disc: unknown, target: string, title?: string) => ipcRenderer.invoke("axm:backupDisc", disc, target, title),
  findDiscBackup: (disc: unknown, target: string, title?: string) => ipcRenderer.invoke("axm:findDiscBackup", disc, target, title),
  guessDiscTitle: (label: string) => ipcRenderer.invoke("axm:guessDiscTitle", label),
  remotePlayStatus: () => ipcRenderer.invoke("axm:remotePlayStatus"),
  installRemotePlay: () => ipcRenderer.invoke("axm:installRemotePlay"),
  launchRemotePlay: () => ipcRenderer.invoke("axm:launchRemotePlay"),
  onRemotePlayExit: (callback: () => void) => {
    ipcRenderer.on("axm:remotePlayExit", () => callback());
  },
  steamTrophyGames: () => ipcRenderer.invoke("axm:steamTrophyGames"),
  steamAchievements: (appid: string) => ipcRenderer.invoke("axm:steamAchievements", appid),
  raTrophyGames: () => ipcRenderer.invoke("axm:raTrophyGames"),
  raAchievements: (gameId: string) => ipcRenderer.invoke("axm:raAchievements", gameId),
  raVerify: (username: string, apiKey: string) => ipcRenderer.invoke("axm:raVerify", username, apiKey),
  runningGame: () => ipcRenderer.invoke("axm:runningGame"),
  quitRunningGame: () => ipcRenderer.invoke("axm:quitRunningGame"),
  connectionStatus: () => ipcRenderer.invoke("axm:connectionStatus"),
  setWifiEnabled: (enabled: boolean) => ipcRenderer.invoke("axm:setWifiEnabled", enabled),
  connectionTest: () => ipcRenderer.invoke("axm:connectionTest"),
  manualUrl: () => ipcRenderer.invoke("axm:manualUrl"),
  assistantStatus: () => ipcRenderer.invoke("axm:assistantStatus"),
  ttsStatus: () => ipcRenderer.invoke("axm:ttsStatus"),
  installTts: () => ipcRenderer.invoke("axm:installTts"),
  removeTts: () => ipcRenderer.invoke("axm:removeTts"),
  startTts: () => ipcRenderer.invoke("axm:startTts"),
  speak: (text: string) => ipcRenderer.invoke("axm:speak", text),
  pickVoiceClip: () => ipcRenderer.invoke("axm:pickVoiceClip"),
  resetVoiceClip: () => ipcRenderer.invoke("axm:resetVoiceClip"),
  toolsState: () => ipcRenderer.invoke("axm:toolsState"),
  installTools: () => ipcRenderer.invoke("axm:installTools"),
  startVoice: (micId: string) => ipcRenderer.invoke("axm:startVoice", micId),
  stopVoice: () => ipcRenderer.invoke("axm:stopVoice"),
  onVoice: (callback: (message: unknown) => void) => {
    ipcRenderer.on("axm:voiceText", (_e, message) => callback(message));
  },
  checkForUpdate: () => ipcRenderer.invoke("axm:checkForUpdate"),
  downloadUpdate: (assetUrl: string, assetName: string) => ipcRenderer.invoke("axm:downloadUpdate", assetUrl, assetName),
  openUpdate: (file: string) => ipcRenderer.invoke("axm:openUpdate", file),
  installAssistantModel: () => ipcRenderer.invoke("axm:installAssistantModel"),
  removeAssistantModel: () => ipcRenderer.invoke("axm:removeAssistantModel"),
  createMediaFolder: (parentDir: string, name: string) => ipcRenderer.invoke("axm:createMediaFolder", parentDir, name),
  getSongInfo: (filePath: string) => ipcRenderer.invoke("axm:getSongInfo", filePath),
  getScreenInfo: (title: string, year: string, kind: string, tmdbId?: string) => ipcRenderer.invoke("axm:getScreenInfo", title, year, kind, tmdbId),
  copyMedia: (kind: string, source: string, target: string) => ipcRenderer.invoke("axm:copyMedia", kind, source, target),
  jellyfinDownload: (login: unknown, itemId: string, name: string, kind: string, target: string, container: string) =>
    ipcRenderer.invoke("axm:jellyfinDownload", login, itemId, name, kind, target, container),
  onTransfer: (callback: (progress: unknown) => void) => {
    ipcRenderer.on("axm:transfer", (_e, progress) => callback(progress));
  },
  onResolution: (callback: (state: unknown) => void) => {
    ipcRenderer.on("axm:resolution", (_e, state) => callback(state));
  },
  getResolution: () => ipcRenderer.invoke("axm:getResolution"),
  browserOpen: (url: string) => ipcRenderer.invoke("axm:browserOpen", url),
  browserClose: () => ipcRenderer.invoke("axm:browserClose"),
  browserInput: (action: string) => ipcRenderer.invoke("axm:browserInput", action),
  onBrowserClosed: (callback: () => void) => {
    ipcRenderer.on("axm:browserClosed", () => callback());
  },
  onBrowserNav: (callback: (state: unknown) => void) => {
    ipcRenderer.on("axm:browserNav", (_e, state) => callback(state));
  },
  overlayClose: () => ipcRenderer.invoke("axm:overlayClose"),
  overlayToggle: () => ipcRenderer.invoke("axm:overlayToggle"),
  overlayState: () => ipcRenderer.invoke("axm:overlayState"),
  onOverlay: (callback: (state: { active: boolean }) => void) => {
    ipcRenderer.on("axm:overlay", (_e, state) => callback(state));
  },
  getSteamLibrary: () => ipcRenderer.invoke("axm:getSteamLibrary"),
  installSteamGame: (appid: number) => ipcRenderer.invoke("axm:installSteamGame", appid),
  launchSteamApp: (appid: number) => ipcRenderer.invoke("axm:launchSteamApp", appid),
  openFolder: (dirPath: string) => ipcRenderer.invoke("axm:openFolder", dirPath),
  getLaunchers: () => ipcRenderer.invoke("axm:getLaunchers"),
  openLauncher: (id: string) => ipcRenderer.invoke("axm:openLauncher", id),
  onArtUpdated: (callback: (update: { gameId: string; iconPath?: string; heroPath?: string }) => void) => {
    ipcRenderer.on("axm:artUpdated", (_e, update) => callback(update));
  },
  quit: () => ipcRenderer.invoke("axm:quit"),
};

contextBridge.exposeInMainWorld("axm", api);

export type AxmApi = typeof api;
